spring.application.name=wfinance
# Conex�o
spring.datasource.url=jdbc:postgresql://localhost:5432/wfinance
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
springdoc.api-docs.enabled=true
spring.flyway.enabled=false

rabbitmq.queuename=REGISTER_USER_QUEUE
server.port=8081